language: ruby

env:
  global:
  - JAI_JAR="jai-codec-1.1.3.jar"
  # Boo third party repos but transitive deps are transitive deps :-(
  - JAI_REPO="https://repository.jboss.org/maven2"
  matrix:
  - "CANTALOUPE_VERSION=stable"
  - "CANTALOUPE_VERSION=dev"

services:
- docker

# Upgrade Docker to the current version
before_install:
- .travis/upgrade.sh
- curl "$JAI_REPO/com/sun/media/jai-codec/1.1.3/$JAI_JAR" > "/tmp/$JAI_JAR"
- >
  mvn install:install-file -Dfile="/tmp/$JAI_JAR" -DgroupId="com.sun.media" \
    -DartifactId="jai-codec" -Dversion="1.1.3" -Dpackaging="jar"

before_script:
- bundle exec rubocop

script:
- travis_retry bundle exec rake test_$CANTALOUPE_VERSION

after_success:
- .travis/deploy.sh

# We want all PRs built but only merges on master branch
branches:
  only:
  - master

notifications:
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_success: change
    on_failure: change

#
# Things one needs to set in their project's online Travis configuration
#
# DOCKER_PASSWORD - For logging into the Docker registery (e.g., DockerHub)
# DOCKER_USERNAME - For logging into the Docker registery (e.g., DockerHub)
# AUTH_TOKEN - For querying GitHub releases (otherwise, it's rate limited)
# REG_USERNAME - The DockerHub user or organization that owns the project
# REG_PROJECT - The DockerHub project to which the tagged image is being pushed
# MASTER_BRANCH - The Git branch fromw which you want to push to the registry
# COMMIT_REF [Optional] - A tag, branch, or commit hash from which to build
#
