language: java

env:
- BUILD_TYPE=""
- BUILD_TYPE="-DdevBuild"
- BUILD_TYPE="" ADDED_LIBS="-Dkakadu.version=${KAKADU_VERSION}"
- BUILD_TYPE="-DdevBuild" ADDED_LIBS="-Dkakadu.version=${KAKADU_VERSION}"

jobs:
  exclude:
  - if: env(BUILD_TYPE) IS present AND type != cron

services:
- docker

before_install:
- >-
  openssl aes-256-cbc -K $encrypted_3fc12ce230ac_key -iv $encrypted_3fc12ce230ac_iv
  -in src/test/resources/kakadu_github_key.enc -out kakadu_github_key -d
- chmod 600 kakadu_github_key
- eval $(ssh-agent -s)
- ssh-add kakadu_github_key

install: true

script: >-
      travis_retry mvn deploy $BUILD_TYPE $ADDED_LIBS
      -Ddocker.registry.username="${DOCKER_USERNAME}"
      -Ddocker.registry.password="${DOCKER_PASSWORD}"
      -Ddocker.registry.account="${DOCKER_REGISTRY_ACCOUNT}"
      -Dorg.slf4j.simpleLogger.log.net.sourceforge.pmd=error

# We want all PRs built, but only merges on the 'main' branch
branches:
  only:
  - main

notifications:
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_success: change
    on_failure: change
  pushover:
    if: type == cron AND branch == main
    api_key: "${PUSHOVER_API_KEY}"
    users:
      - "${PUSHOVER_USER_KEY}"
    template: "%{repository_slug} (%{commit}) : %{message} - Build details: %{build_url}"
    on_success: never
    on_failure: always
