version: '3.4'
services:
  cantaloupe:
    image: uclalibrary/cantaloupe-ucla:4.1.4
    ports:
      - "8182:8182"
    deploy:
      replicas: 1
    container_name: melon
    env_file:
      - .docker-compose-test-delegate.env
    volumes:
      - ./cantaloupe_home:/usr/local/cantaloupe
