apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cantaloupe.fullname" . }}
  labels:
    {{- include "cantaloupe.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.cantaloupe.env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
