apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cantaloupe.fullname" . }}
  labels:
    {{- include "cantaloupe.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "cantaloupe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "cantaloupe.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cantaloupe.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - -c
            - docker-entrypoint.sh && exec java -Dcantaloupe.config=$CONFIG_FILE -XX:ActiveProcessorCount=4 -Xmx$HEAP_SIZE -jar /usr/local/cantaloupe/cantaloupe-*.*ar
          command:
            - sh
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.cantaloupe.env .Values.cantaloupe.envSecrets }}
          env:
            {{- range $k, $v := .Values.cantaloupe.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- range $k, $v := .Values.cantaloupe.envSecrets }}
            - name: {{ $k }}
              valueFrom:
                secretKeyRef:
                  name: {{ $v }}
                  key: {{ $k | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.cantaloupe.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /iiif/2
              port: {{ .Values.cantaloupe.port }}
          readinessProbe:
            httpGet:
              path: /iiif/2
              port: {{ .Values.cantaloupe.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
