{{- if .Values.cantaloupe.externalSecrets.enabled -}}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "cantaloupe.fullname" . }}-external
  labels:
    {{- include "cantaloupe.labels" . | nindent 4 }}
spec:
  backendType: {{ .Values.cantaloupe.externalSecrets.backend | default "systemManager" | quote }}
  data:
    {{- range $k, $v := .Values.cantaloupe.externalSecrets.env }}
    - key: {{ $v }}
      name: {{ $k }}
    {{- end }}
{{- end }}
