apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cantaloupe.fullname" . }}
  labels:
    {{- include "cantaloupe.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.cantaloupe.secrets.env }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
