name: Draft Release

# Any time new commits hit the 'main' branch, add them to the next release draft
on:
  push:
    branches:
      - main

jobs:
  draft-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 # v6.0.0
        with:
          config-name: configs/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
